# Generated by Django 4.2.19 on 2026-03-18 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileIntegrityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_by', models.CharField(max_length=100)),
                ('rse_expression', models.CharField(blank=True, max_length=255, null=True)),
                ('full_scan', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SUBMITTED', max_length=20)),
                ('job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('logs', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_integrity_checker_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('lfn', models.CharField(max_length=512)),
                ('rse', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='file_integrity_checker.fileintegrityrequest')),
            ],
            options={
                'db_table': 'file_integrity_checker_replicas',
            },
        ),
    ]
