# Generated by Django 4.2.19 on 2026-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_integrity_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereplica',
            name='pfn',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
