# PersistentVolumeClaim used to mount CMS cvmfs area in pods
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-cvmfs-cms-pvc
  namespace: dmtops-crons
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-cms