# Services used to open node ports for Spark communications
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port
      nodePort: 31203
      port: 31203
      protocol: TCP
      targetPort: 31203
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31204
      port: 31204
      protocol: TCP
      targetPort: 31204
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-1
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-1
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31205
      port: 31205
      protocol: TCP
      targetPort: 31205
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31206
      port: 31206
      protocol: TCP
      targetPort: 31206
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-2
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-2
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31207
      port: 31207
      protocol: TCP
      targetPort:  31207
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31208
      port: 31208
      protocol: TCP
      targetPort: 31208
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-3
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-3
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31209
      port: 31209
      protocol: TCP
      targetPort: 31209
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31210
      port: 31210
      protocol: TCP
      targetPort: 31210
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-4
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-4
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31213
      port: 31213
      protocol: TCP
      targetPort: 31213
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31214
      port: 31214
      protocol: TCP
      targetPort: 31214
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-5
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-5
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31215
      port: 31215
      protocol: TCP
      targetPort: 31215
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31216
      port: 31216
      protocol: TCP
      targetPort: 31216
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-6
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-6
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31217
      port: 31217
      protocol: TCP
      targetPort: 31217
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31218
      port: 31218
      protocol: TCP
      targetPort: 31218
---
# Service used to open node ports for Spark communication
# WARNING: The same ports can't be used in parallel for different spark-jobs
kind: Service
apiVersion: v1
metadata:
  name: dmtops-spark-svc-7
  namespace: {{ .Values.dmops_namespace }}
spec:
  selector:
    app: dmtops-spark-svc-7
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31219
      port: 31219
      protocol: TCP
      targetPort: 31219
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31220
      port: 31220
      protocol: TCP
      targetPort: 31220