apiVersion: batch/v1
kind: CronJob
metadata:
  name: integrity-jobs-cleanup
spec:
  schedule: "0 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: integrity-cleanup
              image: registry.paas.cern.ch/file-invalidation-tool/file-invalidation-tool:latest
              command: ["python3", "file_integrity_checker/cleanup_jobs.py"]
              volumeMounts:
                - name: integrity-input-file
                  mountPath: "/shared-data-integrity"
          restartPolicy: Never
          serviceAccountName: job-runner
          volumes:
            - name: integrity-input-file
              persistentVolumeClaim:
                claimName: integrity-input-file-pvc