apiVersion: batch/v1
kind: CronJob
metadata:
  name: jobs-log-processor
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  successfulJobsHistoryLimit: 2 
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: invalidation-log-processor
            image: registry.paas.cern.ch/file-invalidation-tool/file-invalidation-tool:latest
            imagePullPolicy: Always
            command: ["python3", "fi_manager/process_jobs.py"]
          - name: integrity-log-processor
            image: registry.paas.cern.ch/file-invalidation-tool/file-invalidation-tool:test
            imagePullPolicy: Always
            command: ["python3", "file_integrity_checker/process_jobs.py"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secret-key
                      key: SECRET_KEY
                - name: JIRA_PAT
                  valueFrom:
                    secretKeyRef:
                      name: jira-pat
                      key: JIRA_PAT
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: django-db-name
                      key: DB_NAME
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: django-db-host
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: django-db-port
                      key: DB_PORT
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: django-db-user
                      key: DB_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: django-db-password
                      key: DB_PASSWORD
            volumeMounts:
                - name: integrity-input-file
                  mountPath: /shared-data-integrity
          volumes:
            - name: integrity-input-file
              persistentVolumeClaim:
                claimName: integrity-input-file-pvc
          restartPolicy: Never
          serviceAccountName: job-reader