#! /usr/bin/env python3

import base64
import json
import logging
import os
import traceback
from argparse import ArgumentParser

import gitlab
from rucio.client import Client

from CMSRSE import CMSRSE

SKIP_SITES = []

# PoC hardcoded list of RSE names for which _User variants should be created
USER_TIER_POC_SITES = ['T2_IT_Rome']

parser = ArgumentParser(description="Update a site definition from GitLab")
parser.add_argument('--type', dest='cms_type', help='type of RSE (prod-real, int-real, test, temp, user).',
                    default=None, required=True)
parser.add_argument('--dryrun', dest='dry_run', action='store_true',
                    help='do not change anything in rucio, checking only')

parser.add_argument('--debug', action='store_true', help="be more verbose=")

options = parser.parse_args()

# Get all the projects from GitLab
private_token = os.environ['GITLAB_TOKEN']
gl = gitlab.Gitlab('https://gitlab.cern.ch', private_token=private_token)
group = gl.groups.get('siteconf')
projects = group.projects.list(all=True)

logger = logging.getLogger("setRucioFromGitlab")
logger = logging.getLogger()
fh = logging.StreamHandler()
fh_formatter = logging.Formatter('%(asctime)s  %(levelname)s - %(message)s', datefmt='%Y%m%d %H:%M:%S')
fh.setFormatter(fh_formatter)
logger.addHandler(fh)

if options.debug:
    logger.setLevel(level=logging.DEBUG)
else:
    logger.setLevel(level=logging.INFO)


client = Client()


rses = client.list_rses('update_from_json=True')
DO_SITES = [rse['rse'] for rse in rses]
for project in projects:
    full_project = gl.projects.get(project.id)
    try:
        f = full_project.files.get('storage.json', 'master')
        sites = json.loads(base64.b64decode(f.content))
        for site in sites:
            if 'rse' not in site:
                print(f"Error: No RSE entry found for {site['site']}. Skipping.")
                continue
            print(f'Checking {site["rse"]} and type {options.cms_type}')
            if site['rse'] and options.cms_type in ['test', 'temp']:
                # For test and temp types, apply to all RSEs
                if options.cms_type == 'test':
                    rse_name = site['rse'] + '_Test'
                    deterministic = True
                elif options.cms_type == 'temp':
                    rse_name = site['rse'] + '_Temp'
                    deterministic = False
                if rse_name in SKIP_SITES or not DO_SITES or rse_name not in DO_SITES:
                    print(' Skipping.')
                    continue

                rse = CMSRSE(site, dry=options.dry_run, cms_type=options.cms_type, deterministic=deterministic)
                try:
                    if rse.update():
                        print(f'RSE {rse.rse_name} and type {rse.rucio_rse_type} changed')
                    else:
                        print(f'RSE {rse.rse_name} and type {rse.rucio_rse_type} unchanged')
                except Exception:
                    print(f'Could not update RSE {rse.rse_name}. Traceback:')
                    print(traceback.format_exc())
            elif site['rse'] and options.cms_type == 'user':
                # For user type, only create _User variants for PoC sites
                if site['rse'] not in USER_TIER_POC_SITES:
                    print(f' Skipping (not in PoC list: {USER_TIER_POC_SITES})')
                    continue
                # For these, query the actual site and construct a JSON
                rse_name = site['rse'] + '_User'
                deterministic = True
                # Allow PoC _User RSEs to be created even if not yet in Rucio
                if rse_name in SKIP_SITES:
                    print(' Skipping.')
                    continue

                rse = CMSRSE(site, dry=options.dry_run, cms_type=options.cms_type, deterministic=deterministic)
                try:
                    if rse.update():
                        print(f'RSE {rse.rse_name} and type {rse.rucio_rse_type} changed')
                    else:
                        print(f'RSE {rse.rse_name} and type {rse.rucio_rse_type} unchanged')
                except Exception:
                    print(f'Could not update RSE {rse.rse_name}. Traceback:')
                    print(traceback.format_exc())
            elif options.cms_type in ['prod-real', 'int-real']:
                if site['rse'] in SKIP_SITES or not DO_SITES or site['rse'] not in DO_SITES:
                    print(' Skipping.')
                    continue

                if 'fts' not in site:
                    site.update({'fts': ["https://fts3-cms.cern.ch:8446", "https://lcgfts3.gridpp.rl.ac.uk:8446"]})
                rse = CMSRSE(site, dry=options.dry_run, cms_type=options.cms_type)
                try:
                    if rse.update():
                        print(f'RSE {rse.rse_name} and type {rse.rucio_rse_type} changed')
                    else:
                        print(f'RSE {rse.rse_name} and type {rse.rucio_rse_type} unchanged')
                except Exception:
                    print(f'Could not update RSE {rse.rse_name}. Traceback:')
                    print(traceback.format_exc())
            elif not site['rse']:
                print(f'No RSE defined in JSON {site}')
    except (gitlab.exceptions.GitlabGetError, json.decoder.JSONDecodeError):
        print(f"Unable to download or decode storage.json for {project.name}")
