apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rucio-consistency.fullname" . }}-consistency-config
data:
  config.yaml: |+
    rses:
      "*": # default
        include_sizes: no
        partitions:     5
{{- with .Values.consistency.ignore }}
        ignore_list:
{{ toYaml . | indent 12 }}
{{- end }}
        scanner:
          recursion:      1
          nworkers:       3
          timeout:        300
{{- if  (.Values.consistency.filter) }}
          filter: {{ .Values.consistency.filter }}
{{- end }}
          server_root: {{.Values.consistency.defaultRoot }}
          remove_prefix: /
          add_prefix: /
          roots:
          - path: /store/express
          - path: /store/mc
          - path: /store/data
          - path: /store/generator
          - path: /store/results
          - path: /store/hidata
          - path: /store/himc
          - path: /store/relval
        dbdump:
{{- if  (.Values.consistency.filter) }}
          filter: {{ .Values.consistency.filter }}
{{- end }}
          path_root:   /
        dark_action:
          max_fraction: 0.01
          max_age_last_run: 3
          confirmation_window: 35
          min_age_first_run: 25
          min_runs: 3
        missing_action:
          max_fraction: 0.01
          max_age_last_run: 3


{{ range $site, $config := .Values.consistency.sites }}
      {{ $site }}:
{{- if $config }}
{{- if or (or $config.server $config.server_root) (or $config.timeout (hasKey $config "is_redirector")) }}
        scanner:
{{- if  ($config.server) }}
          server: {{ $config.server }}
{{- end }}
{{- if  ($config.server_root) }}
          server_root: {{ $config.server_root }}
{{- end }}
{{- if  ($config.timeout) }}
          timeout: {{ $config.timeout }}
{{- end }}
{{- if (hasKey $config "is_redirector") }}
          is_redirector: {{ $config.is_redirector }}
{{- end }}
{{- end }}
{{- if or $config.minagedark $config.maxdarkfraction }}
        dark_action:
{{- if  ($config.minagedark) }}
          min_age_first_run: {{ $config.minagedark }}
{{- end }}
{{- if  ($config.maxdarkfraction) }}
          max_fraction: {{ $config.maxdarkfraction }}
{{- end }}
{{- end }}
{{- if  ($config.maxmissfraction) }}
        missing_action:
          max_fraction: {{ $config.maxmissfraction }}
{{- end }}
{{- end }}
{{- end }}
