# Default values for rucio-cron-jobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cmssw/rucio_client
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

dmops_image:
  repository: registry.cern.ch/cmsrucio/dmops-spark-crons
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

dmops_namespace: "dmtops"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cronjobSettings:
  daemonName: "cms-ruciod-prod"
  instance: "prod"
  additionalEnvs:
    - name: USERCERT_NAME
      value: "rootcert.pem"
    - name: USERKEY_NAME
      value: "rootkey.pem"

cronjobs:
  - name: rucio-subscriptions
    app: dmtops-spark-svc
    schedule: "10 6 * * *"
    cvmfs: false
    command: 
      - /src/submit_rucio_subscriptions.sh
    ports:
      driver: 31203
      blockManager: 31204
  - name: rucio-account-usage-locks
    app: dmtops-spark-svc-1
    schedule: "30 6 * * *" 
    cvmfs: false
    command: 
      - /src/submit_rucio_account_usage_locks.sh
    ports:
      driver: 31205
      blockManager: 31206
  - name: rucio-account-usage
    app: dmtops-spark-svc-2
    schedule: "*/5 * * * *" 
    cvmfs: false
    command: 
      - /src/submit_rucio_account_usage.sh
    ports:
      driver: 31207
      blockManager: 31208
  - name: rucio-activity-usage
    app: dmtops-spark-svc-3
    schedule: "13 3 * * *"
    cvmfs: false
    command: 
      - /src/submit_rucio_activity_usage.sh
    ports:
      driver: 31209
      blockManager: 31210
  - name: rucio-rules-count-volume
    app: dmtops-spark-svc-4
    schedule: "10 7 * * *"
    cvmfs: false
    command: 
      - /src/submit_rucio_rules_count_volume.sh
    ports:
      driver: 31213
      blockManager: 31214
  - name: rucio-activity-account-usage
    app: dmtops-spark-svc-5
    schedule: "13 3 * * *"
    cvmfs: false
    command: 
      - /src/submit_rucio_activity_account_usage.sh
    ports:
      driver: 31215
      blockManager: 31216
  - name: rucio-locks-count-volume
    app: dmtops-spark-svc-6
    schedule: "10 7 * * *"
    cvmfs: false
    command: 
      - /src/submit_rucio_locks_count_volume.sh
    ports:
      driver: 31217
      blockManager: 31218
  - name: rucio-errors-volume
    app: dmtops-spark-svc-7
    schedule: "*/5 * * * *"
    cvmfs: false
    command: 
      - /src/submit_rucio_errors_volume.sh
    ports:
      driver: 31219
      blockManager: 31220
  - name: rucio-summary
    schedule: "*/5 * * * *" 
    cvmfs: true
    command: 
      - /src/run_rucio_summary.sh
  - name: rse-usage
    schedule: "*/5 * * * *" 
    cvmfs: false
    command:
      - python3
      - /src/RSE_USAGE.py
  - name: wm-dashboard
    schedule: "0 6 * * *" 
    cvmfs: true
    command:
      - /src/run_wf_dashboard.sh

oidc:
  iamServer: https://cms-auth.web.cern.ch/ 
  iamClientId: da4251a5-70c2-418d-a061-b861e779ed1e

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}