FROM centos:7
RUN yum install -y epel-release.noarch && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN yum upgrade -y && \
    yum clean all && \
    rm -rf /var/cache/yum

# Pull some useful stuff out of git (Temporary)
RUN yum install -y nano git && \
    yum clean all && \
    rm -rf /var/cache/yum


WORKDIR /root
RUN git clone https://github.com/dmwm/CMSRucio.git

# end Temporary


RUN yum install -y python3 python3-pip && \
    yum clean all && \
    rm -rf /var/cache/yum

WORKDIR /tmp

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install rucio-clients

COPY traces /traces

RUN rpm -i https://github.com/dshearer/jobber/releases/download/v1.4.0/jobber-1.4.0-1.el7.x86_64.rpm


ENTRYPOINT ["/traces/run_traces.sh"]
